apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: 40Gi
