apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Values.apptype }}-{{ .Values.appname }}
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: {{ .Values.pvcstorage }}