apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJub2xvZ2luIiwicGFzc3dvcmQiOiJmNDdkYWM4Ni1lODA5LTQ5ODctODQyYy0xNGU2NmVmYzhhZjYiLCJhdXRoIjoiYm05c2IyZHBianBtTkRka1lXTTROaTFsT0RBNUxUUTVPRGN0T0RReVl5MHhOR1UyTm1WbVl6aGhaalk9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2025-11-21T08:17:03Z"
  name: regscw
  namespace: default
  resourceVersion: "522649"
  uid: 022084e8-569d-45f5-a034-8301a7a50f40
type: kubernetes.io/dockerconfigjson
