apiVersion: v1
kind: Secret
metadata:
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
  name: secret-env
type: Opaque
stringData:
  dbuser: root
  dbpasswd: mariadbvultrc179780g543278JKJKGYFQXPVJHoiwiodfsertAPOOQAMU
  dbhost: "svc-cip-mariadb-c2.ns-mariadb-c2.svc.cluster.local"
  dbport: "3306"
  dbname: photos1
  aws_access_key_id: {{ .Values.aws_access_key_id }}
  aws_secret_access_key: {{ .Values.aws_secret_access_key }}
  region_name: "il-central-1"
  endpoint_url: "https://s3.il-central-1.amazonaws.com"
  bucket: "resizernov25"