apiVersion: v1
kind: Service
metadata:
  name: svc-lb-{{ .Values.apptype }}-{{ .Values.appname }}
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
spec:
  selector:
    app: app-{{ .Values.apptype }}-{{ .Values.appname }}
  ports:
    - name: port80
      protocol: TCP
      port: 80
      targetPort: 80

