apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeup-role
  namespace: nodeup
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - create
      - patch
      - update
