apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-{{ .Values.apptype }}-{{ .Values.appname }}
  namespace: ns-{{ .Values.apptype }}-{{ .Values.appname }}
spec:
  serviceName: svc-{{ .Values.apptype }}-{{ .Values.appname }}
  selector:
    matchLabels:
      app: tpl-{{ .Values.apptype }}-{{ .Values.appname }}
  replicas: 1
  template:
    metadata:
      labels:
        app: tpl-{{ .Values.apptype }}-{{ .Values.appname }}
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-{{ .Values.apptype }}-{{ .Values.appname }}
      containers:
      - name: cnt1
        image: {{ .Values.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysqlrootpassword }}
        volumeMounts:
        - name: vol1
          mountPath: /var/lib/mysql

